language: cpp

compiler:
  - clang
# No GCC atm because gcc 4.6 doesn't know about "--std=c++11" and I dont want
# to have extra handling just for GCC.

# Travis' Boost is too old (1.46 I think; it misses boost/atomic.hpp).
# Thus, install a newer one:
before_install:
 - wget http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.bz2
 - tar --bzip2 -xf boost_1_54_0.tar.bz2
 - cd boost_1_54_0
 - ./bootstrap.sh --help
# We only need atomic (and also only header-only).
# All the rest takes way too much time to compile.
 - sudo ./bootstrap.sh --with-libraries="atomic"
# Way too much output, so just display the last 50 lines.
 - sudo ./b2 install | tail -n 50
 - cd ..

env:
  CFLAGS=-I/usr/local/include

install:
  - sudo apt-get update
  - sudo apt-get install python-dev libsnappy-dev libtool
  - sudo apt-get install yasm libchromaprint-dev portaudio19-dev libboost-dev
  - sudo apt-get install libavformat-dev

script:
  - python setup.py build
  - sudo python setup.py install
  - python -c "import musicplayer as mp; p = mp.createPlayer()"
